name: Deploy Todo App

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: SSH into EC2 & Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            pwd  # Print working directory
            ls -la  # Check if the files exist
            cd /home/ubuntu/test/Todos-nodejs/
            git pull origin test

